import google.generativeai as genai


def lda_to_keywords(text, lda_string):
    GOOGLE_API_KEY = "AIzaSyCFb7nxEauCLQ7FAW2odYHkD1oJNmCx264"

    genai.configure(api_key=GOOGLE_API_KEY)
    model = genai.GenerativeModel("gemini-pro")

    system_prompt = f"""
    % Overview
    You are assigned the task of converting the topics generated by Latent Dirichlet Allocation on an input text which is the speech to text rendition of a visitor talking to an alzheimer's patient. The prime reason to generate the keywords summarizing each topic is to analyze them later in order to ensure that the conversation topics are safe for the patient's security.

    % Speech to text of visitors conversation with the Alzheimer's patient
    text = {text}

    % 5 output topics generated using gensim.models.LdaModel
    output = {lda_string}

    % Based on the above data, describe each topic in one keyword/topic name.

    % Output format
    ['keyword1','keyword2','keyword3','keyword4','keyword5']

    ## Strictly follow the output format
    ## Focus on the LDA Topics first, use the text conversation only for reference.
"""
    # messages = system_prompt.format(demographics, symptoms)
    chat = model.start_chat(history=[])
    response = chat.send_message(system_prompt)
    response = response.text
    return response

text = '''
Hey John, how are you doing today?
David? Is that you? Haven't seen you in a while. Where's Mary?
She's at the garden club meeting, John. Remember? We talked about it last week.
Last week? Did we? Feels like ages ago. Mind you, everything feels like ages ago these days.
I know it's tough, John. But that's why I'm here. Brought you some of your favorites – apples and that oatcake you like.
Oatcake! Now you're talking.Mary always hides them, says I eat them all at once.
Well, maybe I can convince her to let you have a little more freedom with the snacks today.  So, what have you been up to, champ?
This… this thing. Can't remember what it's called. Used to play chess all the time with… with… 
Your dad? You and your dad used to have epic chess battles. Remember how you'd always try to trick him with that sneaky queen move?
Dad? Right! Dad. Used to love playing with him. He always beat me, though. Smart man, your dad.
He was a sharp one, that's for sure. Hey, listen, how about we set up a game? Maybe I can get schooled by the master himself?
Master? Hardly. But… a game sounds good. Been a while since I've played. Remember the rules, though?
Of course, John. How about we play for the oatcake? Winner takes all?
Winner takes all? You're on! Don't underestimate the old dog, David.
Wait… where's the knight?
Right here, John. Next to your king. See? Remember, the knight moves in an L-shape.
Ah, the knight. Right. Used to love using the knight for surprise attacks. Like a sneaky little soldier.
My, look at the time! Mary will be home soon.
Don't worry about Mary, John. We still have a few moves left in us, don't we?  Besides, who knows, maybe you can use that sneaky knight to win the oatcake after all.
'''

lda_string = '''
Topic: 0 
Words: 0.048*"remember" + 0.026*"dad" + 0.026*"john" + 0.026*"ago" + 0.026*"like" + 0.026*"age" + 0.026*"feel" + 0.026*"love" + 0.026*"know" + 0.026*"game"
0.048*"remember" + 0.026*"dad" + 0.026*"john" + 0.026*"ago" + 0.026*"like" + 0.026*"age" + 0.026*"feel" + 0.026*"love" + 0.026*"know" + 0.026*"game"


Topic: 1
Words: 0.086*"dad" + 0.068*"chess" + 0.037*"play" + 0.037*"time" + 0.037*"battle" + 0.037*"epic" + 0.037*"good" + 0.037*"game" + 0.037*"sound" + 0.037*"love"
0.086*"dad" + 0.068*"chess" + 0.037*"play" + 0.037*"time" + 0.037*"battle" + 0.037*"epic" + 0.037*"good" + 0.037*"game" + 0.037*"sound" + 0.037*"love"


Topic: 2
Words: 0.058*"like" + 0.058*"oatcake" + 0.040*"remember" + 0.040*"knight" + 0.040*"sneaky" + 0.040*"winner" + 0.040*"take" + 0.040*"right" + 0.022*"move" + 0.022*"queen"        
0.058*"like" + 0.058*"oatcake" + 0.040*"remember" + 0.040*"knight" + 0.040*"sneaky" + 0.040*"winner" + 0.040*"take" + 0.040*"right" + 0.022*"move" + 0.022*"queen"


Topic: 3
Words: 0.074*"john" + 0.051*"mary" + 0.051*"today" + 0.028*"maybe" + 0.028*"remember" + 0.028*"little" + 0.028*"let" + 0.028*"snack" + 0.028*"talking" + 0.028*"hide"
0.074*"john" + 0.051*"mary" + 0.051*"today" + 0.028*"maybe" + 0.028*"remember" + 0.028*"little" + 0.028*"let" + 0.028*"snack" + 0.028*"talking" + 0.028*"hide"


Topic: 4
Words: 0.042*"knight" + 0.042*"john" + 0.042*"mary" + 0.042*"maybe" + 0.042*"master" + 0.042*"week" + 0.023*"right" + 0.023*"david" + 0.023*"oatcake" + 0.023*"win"
0.042*"knight" + 0.042*"john" + 0.042*"mary" + 0.042*"maybe" + 0.042*"master" + 0.042*"week" + 0.023*"right" + 0.023*"david" + 0.023*"oatcake" + 0.023*"win"
'''

